/**
 * Differential tests for contract and off-chain calculations — issue #400.
 *
 * Background
 * ──────────
 * The Soroban `money` crate (`contracts/money/src/lib.rs`) and the backend's
 * `decimal.ts` must agree bit-for-bit on every rounding and allocation
 * operation.  Any divergence — however small — can cause owed-vs-paid
 * comparisons between on-chain state and backend calculations to disagree,
 * silently under- or over-charging borrowers.
 *
 * Approach
 * ────────
 * Because the Rust crate is not compiled or called from Jest, these tests act
 * as a *reference implementation* differential: the TypeScript module is
 * verified against a table of known-good (input, expected-output) pairs that
 * were generated by running the Rust unit tests and recording their results.
 * Every test case in `contracts/money/src/lib.rs` is transcribed here so the
 * two test suites are in lock-step.
 *
 * If the Rust crate is updated (new rounding mode, changed constant, …) the
 * maintainer must update *both* the Rust tests and this file.  CI catches
 * any drift via the `money-policy` job, which re-generates `policy.generated.ts`
 * and `policy.rs` from `money-policy.json` — but it does not diff the test
 * tables, so these differential tests provide the additional safety net.
 *
 * Threat model notes (per issue #400)
 * ─────────────────────────────────────
 * - An off-by-one in a rounding tie-break is a financial discrepancy. Every
 *   tie-break case (abs_remainder * 2 == denominator) must be covered.
 * - `splitProRata` must never fabricate or lose a stroop.  The sum invariant
 *   is verified for all representative fixture cases and a seeded random sweep.
 * - `toStroops` and `fromStroops` must be exact inverses at settlement
 *   precision; excess precision must be rounded, not truncated.
 *
 * Compatibility impact
 * ─────────────────────
 * Read-only tests — zero impact on deployed contracts or persisted data.
 */
import { describe, it, expect } from '@jest/globals';
import {
  roundDiv,
  toStroops,
  fromStroops,
  splitProRata,
  RoundingMode,
  MoneyError,
  STROOP_SCALE,
  STROOP_DECIMALS,
} from '../money/decimal.js';

// ─── Contract fixture table ───────────────────────────────────────────────────
//
// Transcribed from `contracts/money/src/lib.rs` `#[test]` blocks.
// Format: [num, den, mode, expected]

type RoundDivFixture = [bigint, bigint, RoundingMode, bigint];

const ROUND_DIV_CONTRACT_FIXTURES: RoundDivFixture[] = [
  // ── Floor ──────────────────────────────────────────────────────────────
  [7n, 2n, RoundingMode.Floor, 3n],       // 3.5 → 3
  [-7n, 2n, RoundingMode.Floor, -4n],     // -3.5 → -4 (toward -∞)
  [6n, 2n, RoundingMode.Floor, 3n],       // exact
  [1n, 3n, RoundingMode.Floor, 0n],       // 0.333... → 0
  [-1n, 3n, RoundingMode.Floor, -1n],     // -0.333... → -1
  // ── Ceil ───────────────────────────────────────────────────────────────
  [7n, 2n, RoundingMode.Ceil, 4n],        // 3.5 → 4
  [-7n, 2n, RoundingMode.Ceil, -3n],      // -3.5 → -3 (toward +∞)
  [6n, 2n, RoundingMode.Ceil, 3n],        // exact
  [1n, 3n, RoundingMode.Ceil, 1n],        // 0.333... → 1
  [-1n, 3n, RoundingMode.Ceil, 0n],       // -0.333... → 0
  // ── HalfUp ─────────────────────────────────────────────────────────────
  [5n, 2n, RoundingMode.HalfUp, 3n],      // 2.5 ties → away from 0 → 3
  [-5n, 2n, RoundingMode.HalfUp, -3n],    // -2.5 ties → away from 0 → -3
  [7n, 2n, RoundingMode.HalfUp, 4n],      // 3.5 → 4
  [1n, 4n, RoundingMode.HalfUp, 0n],      // 0.25 → 0 (< 0.5)
  [3n, 4n, RoundingMode.HalfUp, 1n],      // 0.75 → 1
  // ── HalfEven (banker's rounding) ───────────────────────────────────────
  [5n, 2n, RoundingMode.HalfEven, 2n],    // 2.5 ties → even → 2
  [7n, 2n, RoundingMode.HalfEven, 4n],    // 3.5 ties → even → 4
  [9n, 2n, RoundingMode.HalfEven, 4n],    // 4.5 ties → even → 4
  [3n, 2n, RoundingMode.HalfEven, 2n],    // 1.5 ties → even → 2
  [-5n, 2n, RoundingMode.HalfEven, -2n],  // -2.5 ties → even → -2
  [-7n, 2n, RoundingMode.HalfEven, -4n],  // -3.5 ties → even → -4
  // ── Exact (no remainder) ───────────────────────────────────────────────
  [10n, 5n, RoundingMode.HalfEven, 2n],
  [0n, 1n, RoundingMode.HalfEven, 0n],
  [-10n, 5n, RoundingMode.HalfEven, -2n],
];

// ─── round_div contract fixtures ─────────────────────────────────────────────

describe('differential: roundDiv vs contracts/money/src/lib.rs (#400)', () => {
  it('matches all Rust unit-test fixtures bit-for-bit', () => {
    for (const [num, den, mode, expected] of ROUND_DIV_CONTRACT_FIXTURES) {
      expect(roundDiv(num, den, mode)).toBe(expected);
    }
  });

  it('throws on division by zero — same error class as Rust MathError::DivByZero', () => {
    expect(() => roundDiv(1n, 0n, RoundingMode.HalfEven)).toThrow(MoneyError);
    expect(() => roundDiv(0n, 0n, RoundingMode.Floor)).toThrow(MoneyError);
  });

  it('handles negative denominator by normalizing sign — matches Rust normalisation', () => {
    // Rust: let (num, den) = if den < 0 { (-num, -den) } ...
    expect(roundDiv(7n, -2n, RoundingMode.Floor)).toBe(roundDiv(-7n, 2n, RoundingMode.Floor));
    expect(roundDiv(-7n, -2n, RoundingMode.Ceil)).toBe(roundDiv(7n, 2n, RoundingMode.Ceil));
  });
});

// ─── Policy constants parity ──────────────────────────────────────────────────

describe('differential: policy constants vs contracts/money/src/policy.rs (#400)', () => {
  it('STROOP_SCALE matches STROOP_SCALE in policy.rs (10_000_000)', () => {
    // policy.rs: pub const STROOP_SCALE: i128 = 10000000;
    expect(STROOP_SCALE).toBe(10_000_000n);
  });

  it('STROOP_DECIMALS matches SCALE in policy.rs (7)', () => {
    // policy.rs: pub const SCALE: u32 = 7;
    expect(STROOP_DECIMALS).toBe(7);
  });
});

// ─── toStroops / fromStroops round-trip ──────────────────────────────────────

describe('differential: toStroops / fromStroops vs contract expectations (#400)', () => {
  it('converts known decimal strings to the expected stroop counts', () => {
    const fixtures: Array<[string, bigint]> = [
      ['0', 0n],
      ['1', 10_000_000n],
      ['0.0000001', 1n],                   // 1 stroop (minimum unit)
      ['1.5', 15_000_000n],
      ['12345678.9', 123_456_789_000_000n],
      ['-1', -10_000_000n],
      ['-0.0000001', -1n],
    ];
    for (const [input, expected] of fixtures) {
      expect(toStroops(input)).toBe(expected);
    }
  });

  it('is the exact inverse of fromStroops at settlement precision', () => {
    const stroopValues: bigint[] = [
      0n,
      1n,
      10_000_000n,
      15_000_000n,
      99_999_999n,
      1_234_567_890_000_000n,
      -1n,
      -10_000_000n,
    ];
    for (const v of stroopValues) {
      expect(toStroops(fromStroops(v))).toBe(v);
    }
  });

  it('rounds excess precision using half-even, never truncates — matches Rust behaviour', () => {
    // 0.00000015 → half-even on 8th digit (1.5 in the extra digit position) →
    // 7th digit was 1 (odd) → round up to 2 → 2 stroops.
    // Rust equivalent: toStroops rounds via round_div, not bit-shift truncation.
    expect(toStroops('0.00000015', RoundingMode.HalfEven)).toBe(2n);
    expect(toStroops('0.00000025', RoundingMode.HalfEven)).toBe(2n); // ties to even
    expect(toStroops('1.00000005', RoundingMode.HalfEven)).toBe(10_000_000n); // rounds down
    expect(toStroops('1.00000015', RoundingMode.HalfEven)).toBe(10_000_002n); // rounds up
  });

  it('rejects malformed input rather than silently returning 0', () => {
    const bad = ['', 'abc', '1.2.3', '1e5', ' ', '--1'];
    for (const input of bad) {
      expect(() => toStroops(input)).toThrow(MoneyError);
    }
  });
});

// ─── split_pro_rata contract fixtures ────────────────────────────────────────

describe('differential: splitProRata vs contracts/money/src/lib.rs split_pro_rata (#400)', () => {
  type SplitFixture = { total: bigint; weights: bigint[]; expected?: bigint[] };

  // Fixtures where we know the exact allocation (cross-checked with the
  // largest-remainder algorithm in the Rust crate).
  const EXACT_FIXTURES: SplitFixture[] = [
    // Equal weights: floor-divide, then remainder goes to index 0.
    { total: 3n, weights: [1n, 1n, 1n], expected: [1n, 1n, 1n] },
    { total: 4n, weights: [1n, 1n, 1n], expected: [2n, 1n, 1n] }, // 1 remainder to idx 0
    { total: 7n, weights: [1n, 1n, 1n, 1n, 1n, 1n, 1n], expected: [1n, 1n, 1n, 1n, 1n, 1n, 1n] },
    // Single weight: full amount
    { total: 1_000_000n, weights: [1n], expected: [1_000_000n] },
    // Zero total: all zeros
    { total: 0n, weights: [3n, 5n, 7n], expected: [0n, 0n, 0n] },
  ];

  it('matches exact-allocation fixtures from the contract crate', () => {
    for (const { total, weights, expected } of EXACT_FIXTURES) {
      const result = splitProRata(total, weights);
      if (expected) {
        expect(result).toEqual(expected);
      }
      // Sum invariant always holds
      expect(result.reduce((a, b) => a + b, 0n)).toBe(total);
    }
  });

  it('sum invariant: parts always equal total — randomised sweep (5 000 cases)', () => {
    // Deterministic xorshift32 — same seed and constants used in
    // decimal.test.ts so a regression shows up in both test files.
    let state = 0x1378_1378 >>> 0;
    const next = (): number => {
      state ^= state << 13;
      state >>>= 0;
      state ^= state >>> 17;
      state ^= state << 5;
      state >>>= 0;
      return state;
    };

    let validCases = 0;
    for (let i = 0; i < 5_000; i++) {
      const n = 1 + (next() % 12);
      const total = BigInt(next() % 1_000_000_000);
      const weights: bigint[] = [];
      for (let j = 0; j < n; j++) {
        weights.push(BigInt(next() % 1_000_000));
      }
      if (weights.every((w) => w === 0n)) continue;
      validCases++;
      const parts = splitProRata(total, weights);
      expect(parts.reduce((a, b) => a + b, 0n)).toBe(total);
      for (const p of parts) expect(p >= 0n).toBe(true);
    }
    expect(validCases).toBeGreaterThan(1000);
  });

  it('never allocates negative amounts', () => {
    const cases: Array<[bigint, bigint[]]> = [
      [1n, [1n]],
      [100n, [50n, 50n]],
      [101n, [50n, 51n]],
      [1_000_000_007n, [3n, 5n, 7n, 11n]],
    ];
    for (const [total, weights] of cases) {
      for (const part of splitProRata(total, weights)) {
        expect(part >= 0n).toBe(true);
      }
    }
  });

  it('throws when total is negative (mirrors Rust invariant check)', () => {
    expect(() => splitProRata(-1n, [1n, 2n])).toThrow(MoneyError);
  });

  it('throws when weights are negative (mirrors Rust invariant check)', () => {
    expect(() => splitProRata(100n, [-1n, 2n])).toThrow(MoneyError);
  });

  it('throws when nonzero total has all-zero weights (Rust: DriftDetected)', () => {
    expect(() => splitProRata(1n, [0n, 0n, 0n])).toThrow(MoneyError);
  });

  it('allows zero total with all-zero weights — returns all zeros', () => {
    expect(splitProRata(0n, [0n, 0n, 0n])).toEqual([0n, 0n, 0n]);
  });

  it('largest-remainder tie-breaking goes to lowest-index among equal remainders', () => {
    // 10 split 3-ways: floor gives [3,3,3], leftover 1 stroop goes to idx 0.
    const result = splitProRata(10n, [1n, 1n, 1n]);
    expect(result[0]).toBe(4n);
    expect(result[1]).toBe(3n);
    expect(result[2]).toBe(3n);
    expect(result.reduce((a, b) => a + b, 0n)).toBe(10n);
  });
});

// ─── Amortization schedule — cross-layer determinism ─────────────────────────

describe('differential: buildAmortizationSchedule cross-layer determinism (#400)', () => {
  // Import lazily to avoid triggering getLoanConfig() before env is set.
  const getSchedule = async () => {
    const { buildAmortizationSchedule } = await import(
      '../services/loanAmortizationService.js'
    );
    return buildAmortizationSchedule;
  };

  const EPOCH = new Date('2024-01-15T00:00:00.000Z');

  beforeEach(() => {
    process.env['LOAN_MIN_SCORE'] = '500';
    process.env['LOAN_MAX_AMOUNT'] = '10000';
    process.env['LOAN_INTEREST_RATE_PERCENT'] = '12';
    process.env['CREDIT_SCORE_THRESHOLD'] = '600';
  });

  afterEach(() => {
    delete process.env['LOAN_MIN_SCORE'];
    delete process.env['LOAN_MAX_AMOUNT'];
    delete process.env['LOAN_INTEREST_RATE_PERCENT'];
    delete process.env['CREDIT_SCORE_THRESHOLD'];
  });

  it('produces a deterministic schedule for a 30-day term (17 280 ledgers)', async () => {
    const build = await getSchedule();
    const schedule = build(1000, 1200 /* 12% bps */, 17280, EPOCH);

    // Pure function — calling twice with the same inputs must return identical
    // objects (no wall-clock time, no Math.random()).
    const schedule2 = build(1000, 1200, 17280, EPOCH);
    expect(schedule).toEqual(schedule2);
  });

  it('totalInterest and totalDue are consistent with principal and rate', async () => {
    const build = await getSchedule();
    // 1000 principal, 12% annual → 120 interest, 1120 total
    const schedule = build(1000, 1200, 17280, EPOCH);
    expect(schedule.principal).toBe(1000);
    expect(schedule.totalInterest).toBe(120);
    expect(schedule.totalDue).toBe(1120);
  });

  it('schedule parts sum to totalDue (no stroop leakage)', async () => {
    const build = await getSchedule();
    const schedule = build(1000, 1200, 17280 * 6 /* 6 months */, EPOCH);
    const partSum = schedule.schedule.reduce((acc, p) => acc + p.totalDue, 0);
    // Allow ±1 cent rounding due to period-by-period rounding accumulation
    expect(Math.abs(partSum - schedule.totalDue)).toBeLessThanOrEqual(0.01);
  });

  it('all period balances are non-negative (no over-repayment modelling)', async () => {
    const build = await getSchedule();
    const schedule = build(500, 800, 17280 * 3, EPOCH);
    for (const period of schedule.schedule) {
      expect(period.runningBalance).toBeGreaterThanOrEqual(0);
    }
  });

  it('final period runningBalance is 0 (loan fully paid)', async () => {
    const build = await getSchedule();
    const schedule = build(100, 1200, 17280, EPOCH);
    const last = schedule.schedule[schedule.schedule.length - 1]!;
    expect(last.runningBalance).toBe(0);
  });
});
